name:
  test
on:
  push
jobs:
  test:
    if: |
      !contains(github.event.head_commit.message, 'WIP')

    strategy:
      matrix:
        nim: ['version-1-4']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: ${{ matrix.nim }}
      - run: "nim --version"
      - run: "nimble -y test"
      - run: "nimble -y install"
      - run: "nimble docgen"
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
